profile_custom_link_field:
  type: string
  default: ""
  description: "The exact name (case sensitive) of the custom user input field used to add an external link on the profile. For example, 'Github username'. If empty, the Discourse username will be used."
profile_custom_link_prefix:
  type: string
  default: ""
  description: "The base url for the external link user input field. For example, 'http://github.com/'."
profile_custom_link_label:
  type: string
  default: ""
  description: "The label that will be used to display the generated link. For example, 'GitHub'."
profile_custom_link_icon:
  default: "external-link-alt"
  description: "The the icon to be used for the external link."
