profile_custom_link_field:
  type: string
  default: ""
profile_custom_link_prefix:
  type: string
  default: ""
profile_custom_link_label:
  type: string
  default: ""
profile_custom_link_icon:
  default: "external-link-alt"